config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  get "welcome/index"

  get "contacts" => "contacts#index"
  get "courses" => "courses#index"
  get "projects" => "projects#index"

  resources :articles, only: [:show] do
    resources :comments do
      member do
        post :like
        post :dislike
      end
    end
  end

  # List articles based on the category
  resources :categories, only: [] do
    resources :articles, only: [:index]
  end

  # Admin routes
  namespace :administrate do
    get "/", to: "dashboards#index"

    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end

    resources :authors do
      member do
        delete :destroy_avatar_image
      end
    end
    resources :categories do
      member do
        delete :destroy_cover_image
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_footer_data
  before_action :store_user_location!, if: :storable_location?

  def set_footer_data
    return if params[:controller].split("/").first == "administrate"

    @footer_categories_1 = Category.all.order(created_at: :asc).limit(4)
    @footer_categories_2 = Category.all.order(created_at: :desc).limit(4)
    @footer_articles = Article.all.sample(4)
  end

  private

  # Its important that the location is NOT stored if:
  # - The request method is not GET (non idempotent)
  # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
  #    infinite redirect loop.
  # - The request is an Ajax request as this can lead to very unexpected behaviour.
  def storable_location?
    request.get? &&
      is_navigational_format? &&
      !devise_controller? &&
      !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  # To redirect to the stored location after the user signs in
  # you would override the after_sign_in_path_for method:
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  # To redirect to the stored location after the user signs out
  # you would override the after_sign_out_path_for method:
  def after_sign_out_path_for(resource_or_scope)
    request.referer if resource_or_scope == :user
    super # logout of the /administrate goes back to home
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_link?(controller_link)
    "active" if controller_name == controller_link
  end
end

app/views/layouts/shared/application/_footer.html.erb
<footer class="section footer-section">
  <div class="container">
    <div class="box-container">
      <div class="box">
        <div class="box-title">Páginas</div>
        <div class="list-container">
          <ul>
            <li><%= link_to 'Início', root_path %></li>
            <li><%= link_to 'Cursos', courses_path %></li>
            <li><%= link_to 'Projetos', projects_path %></li>
            <li><%= link_to 'Contato', contacts_path %></li>
          </ul>
        </div>
      </div>
      <div class="box">
        <div class="box-title">Categorias</div>
        <div class="list-container">
          <ul>
            <% @footer_categories_1.each do |category| %>
              <li><%= link_to category.name, category_articles_path(category) %></li>
            <% end %>
          </ul>
          <ul>
            <% @footer_categories_2.each do |category| %>
              <li><%= link_to category.name, category_articles_path(category) %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="box">
        <div class="box-title">Posts Populares</div>
        <div class="list-container">
          <ul>
            <% @footer_articles.each do |article| %>
              <li><%= link_to article.title, article_path(article) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="social-container">
      <div class="social">
          <%= link_to "https://github.com/ANNEBORTOLI", target: "_blank" do %>
            <%= image_tag "icons/gray/github.svg", alt: "Github" %>
          <% end %>

          <%= link_to "https://www.linkedin.com/in/anne-bortoli/", target: "_blank" do %>
            <%= image_tag "icons/gray/linkedin.svg", alt: "Linkedin" %>
          <% end %>

          <%= link_to "mailto:annebortoli@gmail.com", target: "_blank" do %>
            <%= image_tag "icons/gray/email.svg", alt: "Email" %>
          <% end %>
      </div>
    </div>
    <div class="logo-container">
      <%= image_tag "logo-footer-1.svg", alt:"Logo Footer" %>
      <span class="copyright">2024 - Blog Anne Bortoli. Todos os direitos reservados</span>
    </div>
  </div>
</footer>

app/views/layouts/shared/application/_header.html.erb
<header class="section header-section">
  <div class="container">

    <%= link_to root_path, class: "logo" do %>
      <%= image_tag "logo-1.svg", alt: "Logo Ruby on Rails Club" %>
    <% end %>

    <nav class="menu" id="menu">
      <a href="#" class="close-menu-button" id="closeMenuButton">
        <%= image_tag "icons/white/close.svg", alt: "Close Button" %>
      </a>
      <ul>
        <li><%= link_to 'Início', root_path %></li>
        <li><%= link_to 'Cursos', courses_path %></li>
        <li><%= link_to 'Projetos', projects_path %></li>
        <li><%= link_to 'Contato', contacts_path %></li>
      </ul>
      <div class="mobile-actions">
        <div>
          <%= link_to "Entrar", new_user_session_path, class:"button secondary" unless user_signed_in? %>
          <%= button_to "Sair", destroy_user_session_path, method: :delete, class:"button secondary" if user_signed_in? %>
        </div>
      </div>
    </nav>
    <a href="#" class="open-menu-button" id="openMenuButton">
      <%= image_tag "icons/red/menu.svg", alt:"Open Menu" %>
    </a>
    <div class="actions">
          <%= link_to "Entrar", new_user_session_path, class:"button secondary" unless user_signed_in? %>
          <%= button_to "Sair", destroy_user_session_path, method: :delete, class:"button secondary" if user_signed_in? %>
    </div>
  </div>
</header>